language: node_js
node_js:
  - 0.8
before_script: 
  - npm install -g grunt-cli
branches:
  only:
    - master
env:
  - JQUERIES=1.7.2
  - JQUERIES=1.8.3
  - JQUERIES=1.9.1
  - JQUERIES=git
notifications:
  irc:
    channels:
      - "chat.freenode.net#jquerymobile-dev"
